# Generated by Django 4.1.5 on 2023-01-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_output_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='output_part',
            name='input',
            field=models.IntegerField(default=0),
        ),
    ]
