# Generated by Django 4.1.5 on 2023-01-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=1000)),
                ('input_part', models.TextField(max_length=100)),
                ('output_part', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Output_part',
        ),
        migrations.AddField(
            model_name='testcase',
            name='tnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.TextField(max_length=100),
        ),
    ]
