# Generated by Django 4.1.5 on 2023-01-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usermodel',
        ),
        migrations.AddField(
            model_name='userdata',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
