# Generated by Django 4.1.5 on 2023-01-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userdata_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userdata',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
