# Generated by Django 4.1.5 on 2023-01-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_questionkey_alter_userdata_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnum', models.IntegerField(default=0)),
                ('input', models.CharField(max_length=100)),
                ('output', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnum', models.IntegerField(default=0)),
                ('input', models.CharField(max_length=100)),
                ('output', models.TextField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Testcase',
            new_name='Testcase1',
        ),
    ]
