# Generated by Django 4.1.5 on 2023-01-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_testcase2_testcase3_rename_testcase_testcase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.TimeField()),
                ('time2', models.TimeField()),
                ('time3', models.TimeField()),
                ('time4', models.TimeField()),
                ('time5', models.TimeField()),
            ],
        ),
    ]
