# Generated by Django 4.1.5 on 2023-01-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_tabswitch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabswitch',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='tabswitch',
            name='time3',
        ),
        migrations.RemoveField(
            model_name='tabswitch',
            name='time4',
        ),
        migrations.RemoveField(
            model_name='tabswitch',
            name='time5',
        ),
    ]
