# Generated by Django 4.1.5 on 2023-01-29 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_tabswitch_time2_remove_tabswitch_time3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabswitch',
            name='time1',
        ),
        migrations.AddField(
            model_name='tabswitch',
            name='finish',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 1, 29, 15, 1, 17, 862388)),
        ),
        migrations.AddField(
            model_name='tabswitch',
            name='home',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 1, 29, 15, 1, 17, 862388)),
        ),
        migrations.AddField(
            model_name='tabswitch',
            name='login',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 1, 29, 15, 1, 17, 862388)),
        ),
        migrations.AddField(
            model_name='tabswitch',
            name='test',
            field=models.TimeField(blank=True, default=datetime.datetime(2023, 1, 29, 15, 1, 17, 862388)),
        ),
    ]
