# Generated by Django 4.1.5 on 2023-01-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_tabswitch_time1_tabswitch_finish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LoginTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TestTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='TabSwitch',
        ),
    ]
