# Generated by Django 4.1.5 on 2023-02-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_hidetestcase1_userhidetestcase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHideEvenOdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnum', models.IntegerField(default=0)),
                ('input', models.CharField(max_length=100)),
                ('output', models.TextField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserHideTestcase1',
            new_name='EvenOdd',
        ),
        migrations.RenameModel(
            old_name='HideTestcase1',
            new_name='HideEvenOdd',
        ),
        migrations.DeleteModel(
            name='Testcase1',
        ),
    ]
