# Generated by Django 4.1.5 on 2023-02-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_userhideevenodd_rename_userhidetestcase1_evenodd_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserHideEvenOdd',
            new_name='HideTestcase1',
        ),
        migrations.RenameModel(
            old_name='HideEvenOdd',
            new_name='Testcase1',
        ),
        migrations.RenameModel(
            old_name='EvenOdd',
            new_name='UserHideTestcase1',
        ),
    ]
