# Generated by Django 4.1.5 on 2023-02-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_userhideevenodd_hidetestcase1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HideTestcase1',
        ),
        migrations.DeleteModel(
            name='UserHideTestcase1',
        ),
    ]
