# Generated by Django 4.1.5 on 2023-02-05 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_delete_hidetestcase1_delete_userhidetestcase1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testcase1',
            new_name='EvenOdd',
        ),
    ]
