# Generated by Django 4.1.5 on 2023-02-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_testcase1_evenodd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testcase2',
            new_name='ReverseNum',
        ),
    ]
