# Generated by Django 4.1.5 on 2023-02-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_testcase2_reversenum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testcase3',
            new_name='PrimeNum',
        ),
    ]
