# Generated by Django 4.1.5 on 2023-02-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_hiddenunitnum_unitnum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitNum',
            new_name='HiddenUnitdigit',
        ),
        migrations.RenameModel(
            old_name='HiddenUnitNum',
            new_name='Unitdigit',
        ),
    ]
