# Generated by Django 4.1.5 on 2023-02-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_rename_unitnum_hiddenunitdigit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnum', models.IntegerField(default=0)),
                ('input', models.CharField(max_length=100)),
                ('output', models.TextField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Unitdigit',
            new_name='HiddenUnitNum',
        ),
        migrations.DeleteModel(
            name='HiddenUnitdigit',
        ),
    ]
